
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RLCR
 */
public class frmCategorias extends javax.swing.JFrame {

    /**
     * Creates new form frmCategorias
     */
    public frmCategorias() {
        initComponents();
        this.crear();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtextNombre = new javax.swing.JTextField();
        jtextDescrip = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jbtnEnviar = new javax.swing.JButton();
        BtnSelect = new javax.swing.JButton();
        text = new javax.swing.JLabel();
        cmbcat = new javax.swing.JComboBox<>();
        btncatload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre.setText("Nombre");

        lblDescripcion.setText("Descripcion");

        jbtnEnviar.setText("Enviar");
        jbtnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEnviarActionPerformed(evt);
            }
        });

        BtnSelect.setText("Mostrar");
        BtnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSelectActionPerformed(evt);
            }
        });

        text.setText("mostrar");

        cmbcat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcatActionPerformed(evt);
            }
        });

        btncatload.setText("cargar combo");
        btncatload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncatloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btncatload)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtextDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jbtnEnviar)
                        .addGap(44, 44, 44)
                        .addComponent(BtnSelect))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 196, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion)
                    .addComponent(jtextDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEnviar)
                    .addComponent(BtnSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncatload))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEnviarActionPerformed
        // TODO add your handling code here:
        Conexion cn=new Conexion();
        String descripcion=jtextDescrip.getText();
        String nombre =jtextNombre.getText();
        boolean conec=false;
        try{
            conec= cn.ejecutainsert("INSERT INTO categorias (nombre,descripcion) VALUES ('"+nombre+"','"+descripcion+"')");
                              
                
        }catch(Exception e){
            e.printStackTrace();
        
        }
         if (conec){
                JOptionPane.showMessageDialog( null,"exitoso");
            }  else{
                JOptionPane.showMessageDialog( null,"error");
         }    
        
    }//GEN-LAST:event_jbtnEnviarActionPerformed

    private void BtnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSelectActionPerformed
       List <String> nombre=new ArrayList();
       Conexion cn=new Conexion();
       
        try {
            // TODO add your handling code here:
            
            cn.select("Select nombre from categorias");
            nombre.addAll(cn.select("Select nombre from categorias"));
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmCategorias.class.getName()).log(Level.SEVERE, null, ex);
            
        }
         if(nombre.isEmpty()){
             JOptionPane.showMessageDialog( null,"sin registros");
         }
         else {
             for (String i : nombre) {
                 String cadena=text.getText()+"  "+i;
                 text.setText(cadena+'\n');
             }
         }
        
        
    }//GEN-LAST:event_BtnSelectActionPerformed

    private void btncatloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncatloadActionPerformed
        // TODO add your handling code here:
       List <String> nombre=new ArrayList();
       Conexion cn=new Conexion();
       
        try {
            // TODO add your handling code here:
            
            cn.select("Select nombre from categorias");
            nombre.addAll(cn.select("Select nombre from categorias"));
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmCategorias.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        //listar combobox automatico//
        String vector[]= new String [nombre.size()];
        vector=nombre.toArray(vector);//copiar lista a array igual a vecto//
        cmbcat.setModel(new javax.swing.DefaultComboBoxModel<>(vector ) );//metodo para listar items vector//
        
    }//GEN-LAST:event_btncatloadActionPerformed

    private void cmbcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcatActionPerformed
        // TODO add your handling code here:
        
       btncatload.setText(cmbcat.getSelectedItem().toString());//escuchar opcion//
        
    }//GEN-LAST:event_cmbcatActionPerformed
    public void crear (){
     // TODO add your handling code here:
       List <String> nombre=new ArrayList();
       Conexion cn=new Conexion();
       
        try {
            // TODO add your handling code here:
            
            cn.select("Select nombre from categorias");
            nombre.addAll(cn.select("Select nombre from categorias"));
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmCategorias.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        //listar combobox automatico//
        String vector[]= new String [nombre.size()];
        vector=nombre.toArray(vector);//copiar lista a array igual a vecto//
        cmbcat.setModel(new javax.swing.DefaultComboBoxModel<>(vector ) );//metodo para listar items vector//
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSelect;
    private javax.swing.JButton btncatload;
    private javax.swing.JComboBox<String> cmbcat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnEnviar;
    private javax.swing.JTextField jtextDescrip;
    private javax.swing.JTextField jtextNombre;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
